#!/usr/bin/env bash

###
#  Control CPU Cores settings for P-Cores and E-Cores
###

usage() {
cat << EOF
  Set performance or efficiency cores for 12th Gen Intel systems
  Usage examples:

    set-cores all                       # set all P-Cores enabled
                                        # set all E-Cores enabled

    set-cores performance               # set all P-Cores enabled
                                        # set all E-Cores disabled

    set-cores [ battery | efficiency ]  # set all P-Cores disabled
                                        # set all E-Cores enabled

    set-cores [ list | print | show ]   # show current Core setting state

  Notes:  Can abbreviate to first 3 characters of each command option
EOF
} # end usage()

# SKIP Core 0 - as it is not hot-pluggable and must always
# be online
PCORES=$(echo {01..11})
ECORES=$(echo {12..19})

set_cores () {
  case $1 in
    pcores) CORES=$PCORES ;;
    ecores) CORES=$ECORES ;;
  esac

  case $2 in
    ena*) MODE="-e" ;;
    dis*) MODE="-d" ;;
  esac

  for N in $CORES; do
    sudo chcpu $MODE $N > /dev/null
  done
}

case $1 in
  usage|help) usage; exit 0; ;;
  # "show", "list", or "print" current state
  sh*|li*|pr*)
    echo "Cores list (Core 0 always disabled; it's not hot-pluggable):"
    echo "  performance:  $PCORES"
    echo "  efficiency :  $ECORES"
    echo ""
    lscpu --all --extended
    echo ""

    exit 0
    ;;
  # "performance" only cores
  per*)
    echo "Setting PERFORMANCE mode"
    set_cores pcores enable
    set_cores ecores disable
    ;;
  # "battery" optimized; or "efficiency" only
  bat*|eff*)
    echo "Setting BATTERY OPTIMIZED mode"
    set_cores ecores enable
    set_cores pcores disable
    ;;
  all)
    echo "Setting BATTERY OPTIMIZED mode"
    set_cores pcores enable
    set_cores ecores enable
    ;;
esac

echo "SETTINGS now:"
lscpu --all --extended
echo ""
